### ISSUE TITLE
Wallet compile error

### ISSUE THREAD

**Issue by DArKer08** [teamswipp/swippcore#10]
When I compile new version of wallet with command : `make -j8 -f makefile.unix.` I got

> g++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
> makefile.unix:220: recipe for target 'obj/backtrace.o' failed
> make: *** [obj/backtrace.o] Error 4
> make: *** Waiting for unfinished jobs....
> g++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
> makefile.unix:220: recipe for target 'obj/checkpoints.o' failed
> make: *** [obj/checkpoints.o] Error 4
> 
> 
> g++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
> makefile.unix:220: recipe for target 'obj/addrman.o' failed
> make: *** [obj/addrman.o] Error 4

**Comment by teamswipp** [comment]
Hi @DArKer08. Internal compiler errors from GCC are often the cause of running out of memory. Try reducing the number of threads when compiling (-j2 for example). As Swipp is a C++11 code base you also need to make sure your version of GCC is recent enough (anything over 4.9.0 should work just fine).

**Comment by teamswipp** [comment]
No feedback here, so considering this as resolved and invalid.
