### ISSUE TITLE
remove dependency and functions for curl

### ISSUE THREAD

**Issue by Himan2001** [teamswipp/swippcore#15]
Please remove the curl depended functions from the codebase.

curl makes basicly a static compile under ubuntu 16.04 not possible without build a fat static curl library
itself first.

for the daemon itself the curl function is basicly not nessassary - it makes only sense for the qt-wallet, but the usage of curl makes the binary with all needed extra dependencys very fat.

**Comment by teamswipp** [comment]
The curl dependency is used for fetching information about new releases of the wallet. It is used in the getinfo command of the daemon. It will also be used for additional features in future releases.... Such as blockchain distribution. You can compile curl with a shared library and static linking is not necessary at all. Most (if not all) Linux distributions have a shared version of libcurl included.

Closing.
