### ISSUE TITLE
Problems with PRId64 and mingw32 crosscompile

### ISSUE THREAD

**Issue by Himan2001** [teamswipp/swippcore#16]
Actualy there is an unsolved error when trying to crosscompile with mxe under ubuntu 16.04
and mingw32 with gcc 5.4.

The compiling stops with the usual PRId64 declaration error, which is used in masternode.h

For gcc 5.4 are some extra declarations missing. Please fix the code, so a self compile on ubuntu 14.04 and 16.04 with mxe suite is possible, as usual.

**Comment by teamswipp** [comment]
@Himan2001 How are you invoking the cross compiler?

Cross compiling works. This is how we compile the Windows version of the wallet. How are you cross-compiling? For PRId64 to be defined you need to compile with C++11 enabled. The Swipp code base requires C++11, so don't expect it to work without it.

Our new build system, https://github.com/teamswipp/swippcore-buildsystem will handle compilation under different distro versions. While there is still some work to do on it, most of the functionality works.

**Comment by teamswipp** [comment]
Closing, considering this is another invalid report. For the solution, please refer to the above comment.
